import { useState } from "react";
import { useNavigate } from "react-router";
import { Card, CardContent, CardHeader, CardTitle } from "../components/ui/card";
import { Badge } from "../components/ui/badge";
import { Button } from "../components/ui/button";
import { CheckCircle2, X, RefreshCw } from "lucide-react";

const auditSteps = [
  { label: "Generated", time: "10:15 AM", detail: "Initial question generated by AI for SSE Proficient." },
  { label: "SME Rejected", time: "11:02 AM", detail: "SME rejected — scenario too similar to Q2." },
  { label: "Regenerated with Feedback", time: "11:05 AM", detail: "Regenerated with governance and contractor scenario." },
  { label: "SME Accepted Change", time: "—", detail: "Pending SME decision.", pending: true },
];

export function VersionComparison() {
  const navigate = useNavigate();
  const [decision, setDecision] = useState<string | null>(null);

  return (
    <div className="space-y-6 p-6">
      <div className="space-y-2">
        <h2 className="text-2xl text-[#1F1F29]">Review Proposed Change</h2>
        <p className="text-sm text-gray-600">Compare the original and regenerated question before making a final decision.</p>
      </div>

      {/* Side-by-side comparison */}
      <div className="grid gap-6 md:grid-cols-2">
        <Card className="border-2">
          <CardHeader className="bg-[#F7F7FA]">
            <div className="flex items-center justify-between">
              <CardTitle className="text-sm">Original Version</CardTitle>
              <Badge variant="outline" className="border-red-600 text-red-600 text-xs">Rejected</Badge>
            </div>
          </CardHeader>
          <CardContent className="space-y-4 pt-4">
            <div>
              <p className="text-xs text-gray-500">Question</p>
              <p className="text-xs text-[#1F1F29]">A senior engineer needs to implement custom permission levels for a site collection that meets compliance requirements while restricting document export capabilities. What is the most appropriate approach?</p>
            </div>
            <div>
              <p className="text-xs text-gray-500">Answer</p>
              <p className="text-xs text-[#1F1F29]">Create a custom permission level via Site Settings → Site Permissions → Permission Levels. Select appropriate base permissions, explicitly deny the "Use Remote Interfaces" and "Use Client Integration Features".</p>
            </div>
            <div>
              <p className="text-xs text-gray-500">Previous SME Comment</p>
              <p className="text-xs text-amber-700 italic">"Scenario too similar to Q2 — please use a governance or contractor scenario."</p>
            </div>
          </CardContent>
        </Card>

        <Card className="border-2 border-[#A100FF]">
          <CardHeader className="bg-[#A100FF]/5">
            <div className="flex items-center justify-between">
              <CardTitle className="text-sm">New Proposed Version</CardTitle>
              <Badge className="bg-[#A100FF] text-xs">Regenerated</Badge>
            </div>
          </CardHeader>
          <CardContent className="space-y-4 pt-4">
            <div>
              <p className="text-xs text-gray-500">Question</p>
              <p className="text-xs text-[#1F1F29]">A senior SharePoint engineer is tasked with designing a governance policy for a department site collection, requiring role-based access with restricted download permissions for contractors. How should they configure SharePoint permission inheritance and custom levels?</p>
            </div>
            <div>
              <p className="text-xs text-gray-500">Answer</p>
              <p className="text-xs text-[#1F1F29]">Break permission inheritance at the site collection level, create a custom "Contractor View" permission level excluding "Use Remote Interfaces" and download permissions. Assign contractor accounts to a dedicated SharePoint group with this custom level.</p>
            </div>
            <div className="space-y-1.5">
              <div className="flex justify-between text-xs">
                <span className="text-gray-500">LLM Suggestion Applied</span>
                <Badge className="bg-green-600 text-xs">Yes</Badge>
              </div>
              <div className="flex justify-between text-xs">
                <span className="text-gray-500">Documentation Check</span>
                <Badge className="bg-green-600 text-xs">Aligned</Badge>
              </div>
              <div className="flex justify-between text-xs">
                <span className="text-gray-500">Similarity to Old Version</span>
                <Badge variant="secondary" className="text-xs">0.21 — Low</Badge>
              </div>
              <div className="flex justify-between text-xs">
                <span className="text-gray-500">Duplicate Check</span>
                <Badge className="bg-green-600 text-xs">Passed</Badge>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Decision */}
      {!decision && (
        <Card>
          <CardHeader>
            <CardTitle className="text-base">Decision</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex gap-3">
              <Button className="bg-green-600 hover:bg-green-700" onClick={() => { setDecision("accepted"); setTimeout(() => navigate("/sme-review"), 1200); }}>
                <CheckCircle2 className="mr-2 h-4 w-4" />
                Accept Change
              </Button>
              <Button variant="outline" className="border-red-600 text-red-600" onClick={() => { setDecision("rejected"); setTimeout(() => navigate("/sme-question"), 1200); }}>
                <X className="mr-2 h-4 w-4" />
                Reject Change
              </Button>
              <Button variant="outline" className="border-amber-600 text-amber-700" onClick={() => navigate("/regenerate")}>
                <RefreshCw className="mr-2 h-4 w-4" />
                Regenerate Again
              </Button>
            </div>
          </CardContent>
        </Card>
      )}

      {decision && (
        <Card className={decision === "accepted" ? "border-green-600 bg-green-50" : "border-red-600 bg-red-50"}>
          <CardContent className="pt-5">
            <p className={`text-sm ${decision === "accepted" ? "text-green-800" : "text-red-800"}`}>
              {decision === "accepted" ? "Change accepted. Question updated to the regenerated version." : "Change rejected. Original version remains active."}
            </p>
          </CardContent>
        </Card>
      )}

      {/* Audit timeline */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">Audit Timeline</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-0">
            {auditSteps.map((step, i) => (
              <div key={step.label} className="flex gap-4">
                <div className="flex flex-col items-center">
                  <div className={`flex h-8 w-8 items-center justify-center rounded-full border-2 ${step.pending ? "border-[#D9D9E3] bg-white" : "border-[#A100FF] bg-[#A100FF]"}`}>
                    {step.pending ? (
                      <div className="h-2 w-2 rounded-full bg-[#D9D9E3]" />
                    ) : (
                      <CheckCircle2 className="h-4 w-4 text-white" />
                    )}
                  </div>
                  {i < auditSteps.length - 1 && <div className="my-1 h-8 w-0.5 bg-[#D9D9E3]" />}
                </div>
                <div className="pb-4">
                  <p className={`text-sm ${step.pending ? "text-gray-400" : "text-[#1F1F29]"}`}>{step.label}</p>
                  <p className="text-xs text-gray-500">{step.time} — {step.detail}</p>
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
