[theme]
base = "light"
primaryColor = "#A100FF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F7FA"
textColor = "#1F1F29"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
